### ISSUE TITLE
Installers

### ISSUE THREAD

**Issue by larsk2009** [ProdriveTechnologies/voyager#1]
Hi,

I can't seem to find the installers anywhere. Is that me or are they not being build on Github?

**Comment by maartentamboer** [comment]
We do have github actions, but quite a while back they were disable by an organization policy. I will take a look at this if I can resolve this. In the meantime you can build an installer yourself with the following commands. Currently Python 3.7 is required. I plan to update to Python 3.10 before the end of the year
```
py -3.7 -m venv env
call env/Scripts/activate.bat
python -m pip install --upgrade pip
python -m pip install --upgrade setuptools
python -m pip install --upgrade wheel
pip install -r requirements.txt

pyinstaller deploy/voyager.spec
```
After that use [Inno Setup](https://jrsoftware.org) to build the installer:
```
"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" deploy/Installer.iss
```

**Comment by maartentamboer** [comment]
Fixed: https://github.com/ProdriveTechnologies/voyager/releases/tag/1.16.4
